TaskAppWeb/Controllers/TaskDetailsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskAppWeb.Data;
using TaskAppWeb.Data.Services;
using TaskAppWeb.Models;

namespace TaskAppWeb.Controllers
{
    [Authorize]
    public class TaskDetailsController : Controller
    {
        private readonly ITaskDetailsService _service;

        public TaskDetailsController(ITaskDetailsService service)
        {
            _service = service;

        }
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Description,StartDate,EndDate,Category,Priority,Status")]TaskDetails taskDetails)
        {
            if (!ModelState.IsValid) return View(taskDetails);

            await _service.AddAsync(taskDetails);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var taskDetails = await _service.GetByIdAsync(Id);
            if (taskDetails == null) return View("Not Found");
            return View(taskDetails);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var taskDetails = await _service.GetByIdAsync(Id);
            if (taskDetails == null) return View("Not Found");
            return View(taskDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Description,StartDate,EndDate,Category,Priority,Status")] TaskDetails taskDetails)
        {
            if (!ModelState.IsValid) return View(taskDetails);
            if(Id==taskDetails.Id)
            {
                await _service.UpdateAsync(Id, taskDetails);
                return RedirectToAction(nameof(Index));
            }
            return View(taskDetails);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var taskDetails = await _service.GetByIdAsync(Id);
            if (taskDetails == null) return View("Not Found");
            return View(taskDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var taskDetails = await _service.GetByIdAsync(Id);
            if (taskDetails == null) return View("Not Found");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TaskAppWeb/Controllers/TaskUpdatesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskAppWeb.Data;
using TaskAppWeb.Data.Services;
using TaskAppWeb.Models;

namespace TaskAppWeb.Controllers
{
    [Authorize]
    public class TaskUpdatesController : Controller
    {
        private readonly ITaskUpdatesService _service;
        public TaskUpdatesController(ITaskUpdatesService service)
        {
            _service=service;

        }
        public async Task<IActionResult> Index()
        {
            var updatedata = await _service.GetAllAsync();
            return View(updatedata);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var taskUpdate = await _service.GetByIdAsync(Id);
            if (taskUpdate == null) return View("NotFound");
            return View(taskUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,TaskDetailsId,UpdateInfo,User,DateUpdated")] TaskUpdate taskUpdates)
        {
            if (!ModelState.IsValid) return View(taskUpdates);
            await _service.UpdateAsync(Id, taskUpdates);
            return RedirectToAction(nameof(Index));
        }

    }
}

TaskAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tasks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tasks</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="TaskDetails" asp-action="Index"><i class="bi bi-list-task"></i> Assign tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="TaskUpdates" asp-action="Index"><i class="bi bi-arrow-90deg-up"></i> Update information</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
                @RenderBody()
</main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tasks
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>